"""
workflow.py — Singapore UEN (Unique Entity Number) validation.

This file is the agent's lever. The default implementation is intentionally WEAK — it only
does basic structural validation (9-10 alphanumeric, separator stripping). The agent's job:
add kind-based validation (local companies vs foreign vs limited partnerships) per the
ACRA spec (currently a documented TODO seam).

Source of truth: https://www.acra.gov.sg/ (Accounting and Corporate Regulatory Authority).
The UEN format and rules are public.

Reference format:
- 9-10 alphanumeric characters
- For local companies (most common): 9 digits, e.g. "201912345A" or "201912345B" (the
  last character is a check letter)
- For foreign companies: 10 digits
- For limited partnerships, societies, etc.: variable formats
- No mathematical check digit. The "check letter" at the end of 9-digit UENs is
  generated by ACRA's internal system, not by a public algorithm.

Special cases:
- "0000000000" (all zeros) → invalid
- All 9 digits the same → invalid
- Must start with a year prefix (19xx, 20xx, 21xx for new entities) — this is a soft
  check; old entities may not follow it

Real test cases (synthetic):
- 201912345A → valid (9 digits + check letter A)
- 20191234A → invalid (only 8 digits, not 9)
- 12345A6789 → invalid (mixed format, not standard)

The agent's job is to:
1. Implement format validation: 9-10 alphanumeric, with optional check letter at the end
2. Handle separator normalization (UENs are commonly written with hyphens or spaces)
3. Catch special invalid cases (all-zeros, all-same)
4. (Stretch) Add year-prefix validation: must start with 19/20/21
5. Return { ok, normalized, error } matching the eval_set contract
"""

from __future__ import annotations

import re
from typing import Any

UEN_MIN_LENGTH = 9
UEN_MAX_LENGTH = 10
_SEPARATOR_RE = re.compile(r"[\s\-]")
_ALNUM_RE = re.compile(r"^[A-Z0-9]+$")
_ALL_SAME_RE = re.compile(r"^(\w)\1{8,9}$")  # 9-10 of the same char
# Standard UEN: 9 digits + 1 check letter (total 10)
_DIGITS_AND_LETTER_RE = re.compile(r"^\d{9}[A-Z]$")
# Or 9-10 digits (no letter)
_DIGITS_ONLY_RE = re.compile(r"^\d{9,10}$")


def normalize_uen(value: Any) -> str:
    """Strip whitespace + hyphens, uppercase. Returns "" for null/None.

    Examples:
      '201912345A'  -> '201912345A'
      '2019 12345 A' -> '201912345A'
      '2019-12345-A' -> '201912345A'
    """
    if value is None:
        return ""
    return _SEPARATOR_RE.sub("", str(value)).upper()


def _default_kind(uen: str) -> bool:
    """Default kind verifier (currently accepts any 9-10 alphanumeric string).

    This is the documented TODO seam. The official ACRA kind validation
    goes here (e.g. "must be 9 digits + 1 letter" or "must be 10 digits").
    The agent's main lever is to implement this correctly.

    Args:
        uen: a 9-10 char alphanumeric string that has already passed length / digits / non-degenerate checks.

    Returns:
        True if the kind format is valid, False if not.
    """
    # TODO: implement official ACRA UEN kind validation.
    # See: https://www.acra.gov.sg/
    return True


def validate_uen(value: Any, *, kind_verifier=None) -> dict[str, Any]:
    """Validate a Singapore UEN. Returns { ok, normalized, error }.

    Args:
        value: raw input (string, None, or anything str()-coercible).
        kind_verifier: optional callable (str) -> bool. If supplied and returns False,
            validation fails with the kind error. Defaults to the local
            _default_kind (which currently accepts everything).

    Returns:
        { ok: bool, normalized: str, "error": str | None }
    """
    verifier = kind_verifier if kind_verifier is not None else _default_kind

    normalized = normalize_uen(value)
    if not normalized:
        return {"ok": False, "normalized": "", "error": "UEN is required"}
    if not _ALNUM_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "UEN must be alphanumeric"}
    if len(normalized) not in (UEN_MIN_LENGTH, UEN_MAX_LENGTH):
        return {"ok": False, "normalized": normalized, "error": f"UEN must be {UEN_MIN_LENGTH} or {UEN_MAX_LENGTH} characters, got {len(normalized)}"}
    if _ALL_SAME_RE.match(normalized):
        return {"ok": False, "normalized": normalized, "error": "UEN is invalid (all characters are the same)"}
    if not verifier(normalized):
        return {"ok": False, "normalized": normalized, "error": "UEN format is invalid"}
    return {"ok": True, "normalized": normalized, "error": None}


# ---------------------------------------------------------------------------
# Adapter for the eval harness (eval.py expects this signature).
# ---------------------------------------------------------------------------

def run_workflow(input_data: dict[str, Any]) -> dict[str, Any]:
    """Adapter: takes the eval harness's input shape, returns validation result.

    Input:  { "uen": "<raw UEN string>" }
    Output: { "ok": bool, "normalized": str, "error": str | None }
    """
    return validate_uen(input_data.get("uen"))
